DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE urls
ADD COLUMN IF NOT EXISTS h1_content TEXT,
ADD COLUMN IF NOT EXISTS title_content TEXT,
ADD COLUMN IF NOT EXISTS meta_description TEXT;
